language: python
python:
    - "2.7_with_system_site_packages"
    - "2.6"
    - "3.2"

matrix:
    fast_finish: true
    allow_failures:
        - python: "2.6"
        - python: "3.2"


install:
    - sudo apt-get update
    - LDFLAGS=-lm sudo apt-get install --fix-missing -y $(< requirements)

    - sudo apt-get autoremove -y

    - make setup

script:
    - make test
