language: python
python:
  - '2.7'
  - '3.2'
  - pypy
cache:
  directories:
    - $HOME/.cache/pip
sudo: false
matrix:
  fast_finish: true
  allow_failures:
    - python: '3.2'
    - python: pypy
addons:
  apt:
    packages:
    - libjpeg-dev
    - python-opencv

install:
    - make setup

script:
    - make test
