global
        log 127.0.0.1   local0
        log 127.0.0.1   local1 notice
        maxconn 4096
        user cezar.sa
        group staff
        pidfile /tmp/haproxy.pid
        daemon
        #debug
        #quiet

defaults
        log     global
        mode    http
        option  dontlognull
        option redispatch
        retries 3
        maxconn 2000
        contimeout      5000
        clitimeout      50000
        srvtimeout      50000

listen stats :8080
        balance
        mode http
        stats enable
        stats auth me:password

listen cv :13337
        mode tcp
        option tcplog
        balance roundrobin

        server cv1 localhost:13338 check
        server cv2 localhost:13339 check
        server cv3 localhost:13340 check
